# Generated by Django 2.0.4 on 2018-04-28 20:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduler', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstName', models.CharField(max_length=100)),
                ('lastName', models.CharField(max_length=100)),
                ('dateSubmitted', models.DateField()),
                ('datePartsNeeded', models.DateField()),
                ('facultyAdvisor', models.CharField(max_length=200)),
                ('paymentAccountNo', models.IntegerField()),
                ('className', models.CharField(max_length=100)),
                ('machineRequested', models.CharField(max_length=200)),
                ('listParts', models.CharField(max_length=200)),
            ],
        ),
    ]
